### ISSUE TITLE
lazy symbol binding failed

### ISSUE THREAD

**Issue by logemann** [kosvrouvas/gatsby-tailwindcss-starter#237] opened 2021-04-21 11:03 UTC
after using the starter and firing up "gatsby develop", i am getting:

```
> gatsby develop

success open and validate gatsby-configs - 0.222s
⠋ load plugins
dyld: lazy symbol binding failed: Symbol not found: _g_once_impl
  Referenced from: /Users/ml/development/projects/gatsby/mercedes-abgasskandal/node_modules/sharp/build/Release/sharp.node
  Expected in: /Users/ml/development/projects/gatsby/mercedes-abgasskandal/node_modules/gatsby-plugin-sharp/node_modules/sharp/build/Release/../../vendor/8.10.5/lib/libvips-cpp.42.dylib

dyld: Symbol not found: _g_once_impl
  Referenced from: /Users/ml/development/projects/gatsby/mercedes-abgasskandal/node_modules/sharp/build/Release/sharp.node
  Expected in: /Users/ml/development/projects/gatsby/mercedes-abgasskandal/node_modules/gatsby-plugin-sharp/node_modules/sharp/build/Release/../../vendor/8.10.5/lib/libvips-cpp.42.dylib

error Command failed with signal "SIGKILL".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by kosvrouvas** [comment] 2021-06-14 15:12
_I really need to fix my notifications! :(_ 

This seems to be a problem with Sharp, and I can't reproduce it so maybe an update was applied?

**Comment by kosvrouvas** [comment] 2021-08-17 20:15
Closing this, if you still have a problem feel free to re-open it!

**Closed by kosvrouvas** 2021-08-17 20:15 UTC
